[build]
  # No build command needed for static HTML
  command = ""
  # Directory containing the files to deploy
  publish = "."

[[redirects]]
  # Handle any 404s by serving index.html (for single page apps)
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Use a modern Node.js version
  NODE_VERSION = "18" 